namespace PaketLoadScripts

#r "../../../packages/Newtonsoft.Json/lib/portable-net45+win8+wp8+wpa81/Newtonsoft.Json.dll" 
#r "../../../packages/HtmlAgilityPack/lib/portable-net45+netcore45+wp8+MonoAndroid+MonoTouch/HtmlAgilityPack.dll" 
#r "../../../packages/System.Diagnostics.DiagnosticSource/lib/portable-net45+win8+wpa81/System.Diagnostics.DiagnosticSource.dll" 
#r "../../../packages/System.Collections.Immutable/lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll" 
#r "../../../packages/System.Threading.Tasks.Dataflow/lib/portable-net45+win8+wpa81/System.Threading.Tasks.Dataflow.dll" 
#r "../../../packages/System.Reflection.Metadata/lib/portable-net45+win8/System.Reflection.Metadata.dll" 
#r "System.Security" 
#r "System.Core" 
#r "System" 
#r "System.ComponentModel.Composition" 
#r "System.Configuration" 
#r "System.Xml" 
#r "System.Runtime.Serialization" 
#r "System.Numerics" 
#r "System.IO.Compression" 
#r "System.IO.Compression.FileSystem" 
#r "System.Xaml" 
#r "System.Xml.Linq" 
#r "System.Net.Http" 
#r "Microsoft.CSharp" 
#r "System.Windows" 
#r "System.Windows.Forms" 
#r "WindowsBase" 
#r "System.Runtime" 
#r "ISymWrapper, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
#r "System.IO" 