namespace PaketLoadScripts

#load "System.Collections.Immutable.fsx" 
#load "System.Diagnostics.Process.fsx" 
#load "System.Diagnostics.TraceSource.fsx" 
#load "System.Reflection.Emit.fsx" 
#load "System.Reflection.Metadata.fsx" 
#load "System.Reflection.TypeExtensions.fsx" 
#load "System.Runtime.Loader.fsx" 
#load "System.Security.Cryptography.Algorithms.fsx" 
#load "System.ValueTuple.fsx" 
#r "ISymWrapper, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
#r "System.IO" 
#r "System.Runtime" 
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll" 