namespace PaketLoadScripts

#load "NETStandard.Library.fsx" 
#load "System.ComponentModel.EventBasedAsync.fsx" 
#load "System.ComponentModel.TypeConverter.fsx" 
#load "System.Diagnostics.Process.fsx" 
#load "System.Diagnostics.TextWriterTraceListener.fsx" 
#load "System.Diagnostics.TraceSource.fsx" 
#load "System.Reflection.Metadata.fsx" 
#load "System.Reflection.TypeExtensions.fsx" 
#load "System.Runtime.InteropServices.RuntimeInformation.fsx" 
#load "System.Runtime.Loader.fsx" 
#load "System.Runtime.Serialization.Json.fsx" 
#load "System.Runtime.Serialization.Primitives.fsx" 
#load "System.Threading.Thread.fsx" 
#load "System.Xml.XPath.XmlDocument.fsx" 