namespace PaketLoadScripts

#load "System.Buffers.csx" 
#load "System.Collections.csx" 
#load "System.Diagnostics.Debug.csx" 
#load "System.IO.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Extensions.csx" 
#load "System.Runtime.Handles.csx" 
#load "System.Runtime.InteropServices.csx" 
#load "System.Text.Encoding.csx" 
#load "System.Threading.csx" 
#load "System.Threading.Tasks.csx" 
#r "System.IO.Compression" 