namespace PaketLoadScripts

#load "System.Buffers.fsx" 
#load "System.Collections.fsx" 
#load "System.Diagnostics.Debug.fsx" 
#load "System.IO.fsx" 
#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Extensions.fsx" 
#load "System.Runtime.Handles.fsx" 
#load "System.Runtime.InteropServices.fsx" 
#load "System.Text.Encoding.fsx" 
#load "System.Threading.fsx" 
#load "System.Threading.Tasks.fsx" 
#r "System.IO.Compression" 